import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// Placeholder for Firebase options.
// After running `flutterfire configure` this file will be replaced and will
// export `DefaultFirebaseOptions` and set `firebaseConfigured = true`.
// For now we expose a flag to indicate Firebase is NOT configured.

const bool firebaseConfigured = false;

// When not configured, we provide a harmless stub so analyzer doesn't complain.
// Replace this file with the generated file from `flutterfire configure` for real values.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: '',
        appId: '',
        messagingSenderId: '',
        projectId: '',
      );
}

// Example replacement (generated by `flutterfire configure`):
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform => const FirebaseOptions(
//     apiKey: '...',
//     appId: '...',
//     messagingSenderId: '...',
//     projectId: '...',
//     authDomain: '...',
//     storageBucket: '...',
//   );
// }

