// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const bool firebaseConfigured = true;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-kYwh9vgxi3UFvMC5SHsjFLrY02-Vb0',
    appId: '1:772515931818:web:3cf2c6fa9429054e78d2d3',
    messagingSenderId: '772515931818',
    projectId: 'ahmed-64133',
    authDomain: 'ahmed-64133.firebaseapp.com',
    storageBucket: 'ahmed-64133.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefYERv4iykWPUs4RCaSppCmjNQTFz0To',
    appId: '1:772515931818:android:339ee1582642cceb78d2d3',
    messagingSenderId: '772515931818',
    projectId: 'ahmed-64133',
    storageBucket: 'ahmed-64133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUWNqbIblE62EV8FnlL5cw-2RqreoGfU',
    appId: '1:772515931818:ios:278f7eaf7f7ecf4e78d2d3',
    messagingSenderId: '772515931818',
    projectId: 'ahmed-64133',
    storageBucket: 'ahmed-64133.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOUWNqbIblE62EV8FnlL5cw-2RqreoGfU',
    appId: '1:772515931818:ios:278f7eaf7f7ecf4e78d2d3',
    messagingSenderId: '772515931818',
    projectId: 'ahmed-64133',
    storageBucket: 'ahmed-64133.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-kYwh9vgxi3UFvMC5SHsjFLrY02-Vb0',
    appId: '1:772515931818:web:ecc669c868dafeec78d2d3',
    messagingSenderId: '772515931818',
    projectId: 'ahmed-64133',
    authDomain: 'ahmed-64133.firebaseapp.com',
    storageBucket: 'ahmed-64133.firebasestorage.app',
  );
}
